### PR TITLE
Add ufs-weather-model environment

### PR DESCRIPTION
**Pull request by climbfuji**
The ufs-weather-model environment contains everything to run the ufs-weather-model regression tests manually (ecflow) and automated (ecflow, pygithub, pandas, pyyaml).

### CODE REVIEW

**Comment by christinaholtNOAA** [comment]
@DomHeinzeller Which platforms would this environment be supported on?

**Comment by climbfuji** [comment]
> @DomHeinzeller Which platforms would this environment be supported on?

Right now on gaea and jet, because I maintain the software stack for the ufs-weather-model on these two systems.

**Comment by christinaholtNOAA** [comment]
I am considering breaking this repo out into platform-specific branches because I think deploying all the versions to each machine is going to get confusing. I can make sure to separate this one out into both.

When do you need it installed on Jet? I think Jeff Hamilton and I are the only ones with contrib write privilege at the moment.

**Comment by climbfuji** [comment]
> I am considering breaking this repo out into platform-specific branches because I think deploying all the versions to each machine is going to get confusing. I can make sure to separate this one out into both.
> 
> When do you need it installed on Jet? I think Jeff Hamilton and I are the only ones with contrib write privilege at the moment.

Let's hold off for jet for the moment, because EMC will want to be involved in that (on gaea, I am sharing the maintenance with EMC) and likely we'd want to install the miniconda contrib packages ourselves. Good idea to break this up.

**Comment by climbfuji** [comment]
I am closing this PR since it apparently isn't going anywhere.

**Pull request closed without merging**
